POST http://localhost:3001/api/items/new-item
Content-Type: application/json

{
    "listId": 0,
    "text": "D-Rex",
    "amount": 5,
    "isCompleted": 1,
    "itemId": "sf"
}



# {
#     "newItems": [{
#            "text": "T-Rex",
#            "amount": 2,
#            "price": 1250,
#            "isCompleted": 0,
#          }
#     ]
# }
