POST http://localhost:3001/api/new-item
Content-Type: application/json

{
    "listId": 0,
    "text": "C-Rex",
    "amount": 5,
    "isCompleted": 1
}



# {
#     "newItems": [{
#            "text": "T-Rex",
#            "amount": 2,
#            "price": 1250,
#            "isCompleted": 0,
#          }
#     ]
# }
